/**
 * Turn the template files into the module the studio imports, and into a
 * starter kit somebody can download and work in.
 *
 * The templates used to be backtick literals inside templates.ts, where nobody
 * could find them and where a single backtick ended the literal and broke the
 * module. The files under public/templates are the source now.
 *
 *   npm run templates:build
 *
 * Runs before dev and before build, so neither the generated module nor the
 * kits can be stale.
 *
 * Written as TypeScript and run under tsx so it can import the real library
 * catalogue. The kit's local server needs to know where p5 lives inside its
 * package, and a second copy of that mapping in a build script is a second
 * thing to get wrong.
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { zip } from "./lib/zip.mjs";
import { LIBRARIES } from "../src/lib/runtimes";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const KINDS = ["vanilla", "svg", "p5", "custom"] as const;

const LABEL: Record<string, string> = {
    vanilla: "Canvas 2D",
    svg: "SVG",
    p5: "p5.js",
    custom: "Custom runtime",
};

const missing = KINDS.filter(
    (k) => !existsSync(join(root, "public/templates", k, "index.html")),
);
if (missing.length > 0) {
    console.error(`No template for: ${missing.join(", ")}`);
    process.exit(1);
}

const html = Object.fromEntries(
    KINDS.map((k) => [
        k,
        readFileSync(join(root, "public/templates", k, "index.html"), "utf8"),
    ]),
) as Record<(typeof KINDS)[number], string>;

// --- the module the studio imports ----------------------------------------

const entries = KINDS.map(
    // JSON.stringify, not a template literal. That is the whole point: a
    // backtick or a ${ in someone's template can no longer end the string.
    (kind) => `    ${JSON.stringify(kind)}: ${JSON.stringify(html[kind])},`,
).join("\n");

const module = `// Generated by scripts/build-templates.mts. Do not edit.
//
// The source is public/templates/<kind>/index.html. Edit those, then run
// \`npm run templates:build\`.

export const TEMPLATE_HTML: Record<string, string> = {
${entries}
};

export const TEMPLATE_KINDS = ${JSON.stringify(KINDS)} as const;
`;

const target = join(root, "src/lib/templates.generated.ts");
const before = existsSync(target) ? readFileSync(target, "utf8") : "";
if (before !== module) writeFileSync(target, module);

// --- the starter kits ------------------------------------------------------

/** Where each catalogue library lives inside its published package. */
const paths = Object.fromEntries(
    LIBRARIES.map((l) => [`${l.id}@${l.version}`, l.registry.path]),
);

const serve = readFileSync(join(root, "scripts/kit/serve.mjs"), "utf8").replace(
    "__LIBRARIES__",
    JSON.stringify(paths, null, 4),
);

function readme(kind: string, source: string): string {
    const declared = [...source.matchAll(/content\s*=\s*["']([^"']+)["']/gi)]
        .map((m) => m[1])
        .filter((c) => /^[a-z0-9@._/-]+@[0-9]/i.test(c));

    return `# Aleatory starter: ${LABEL[kind]}

A generative piece, ready to work on. No install and no build step.

## Run it

\`\`\`
node serve.mjs
\`\`\`

Then open http://localhost:4321. Reload for a new seed. Edit \`index.html\`
and reload again. That is the entire loop.

- \`?seed=<hex>\` draws one particular piece, every time.
- \`?p.<name>=<value>\` sets a declared parameter, e.g. \`?p.density=220\`.

You can also open \`index.html\` directly from disk${
        declared.length
            ? ", but this kind declares a library and the server is what loads it, so the file on its own will not draw"
            : ". This kind has no dependencies, so it works either way"
    }.

## What you are editing

\`index.html\` is the whole piece. It is what gets published, byte for byte,
and it is the only file that ends up on chain. \`serve.mjs\` and this README
are for you and are not part of the work.

${
    declared.length
        ? `This piece declares ${declared.join(", ")} in a meta tag:

\`\`\`html
<meta name="alea:library" content="${declared[0]}">
\`\`\`

That tag is how the piece asks for a library. The local server reads it and
loads that library from a CDN; a renderer reads it from the record on chain
and loads a copy it has verified. Either way you never write a script tag
pointing at a CDN, and you should not add one: a piece that fetches anything
while rendering is refused the network, and the capture is of a blank frame.

`
        : ""
}## The three rules

1. **Self-contained.** Nothing fetched while rendering. Declared libraries do
   not count, because the renderer supplies them before your code runs.
2. **Deterministic.** One seed, one image. Draw twice from a fresh page and
   the two agree. Take every random decision from \`$alea\`, never from
   \`Math.random\` or the clock.
3. **Say when you are finished** by calling \`$alea.ready()\`. Forgetting this
   is the one mistake that yields a blank piece: the renderer captures a frame
   because nothing told it the drawing was done.

## Publishing

Drag \`index.html\` into the studio at https://aleatory.art/studio, or paste
it in. Nothing about it needs changing first.

Declaring a library is explained in full at
https://aleatory.art/docs/libraries, and the whole interface at
https://aleatory.art/docs/interface.
`;
}

mkdirSync(join(root, "public/templates"), { recursive: true });

for (const kind of KINDS) {
    const archive = zip([
        { name: "index.html", data: html[kind] },
        { name: "README.md", data: readme(kind, html[kind]) },
        { name: "serve.mjs", data: serve },
    ]);
    writeFileSync(join(root, "public/templates", `${kind}.zip`), archive);
}

console.log(
    `templates: ${KINDS.length} kinds, module ${before === module ? "current" : "written"}, kits zipped`,
);
