/**
 * Turn the template files into the module the studio imports, and into a
 * starter kit somebody can download and work in.
 *
 * The files under public/templates are the source. Keeping them as files
 * rather than literals means a backtick in one cannot break the module.
 *
 *   npm run templates:build
 *
 * Runs before dev and before build, so neither the generated module nor the
 * kits can be stale.
 *
 * Written as TypeScript and run under tsx, alongside the rest of the source.
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { zip } from "./lib/zip.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const KINDS = ["vanilla", "svg", "p5", "custom"] as const;

const LABEL: Record<string, string> = {
    vanilla: "Canvas 2D",
    svg: "SVG",
    p5: "p5.js",
    custom: "Custom runtime",
};

const missing = KINDS.filter((k) => !existsSync(join(root, "public/templates", k, "index.html")));
if (missing.length > 0) {
    console.error(`No template for: ${missing.join(", ")}`);
    process.exit(1);
}

const html = Object.fromEntries(
    KINDS.map((k) => [k, readFileSync(join(root, "public/templates", k, "index.html"), "utf8")]),
) as Record<(typeof KINDS)[number], string>;

const readme = Object.fromEntries(
    KINDS.map((k) => [k, readFileSync(join(root, "public/templates", k, "README.md"), "utf8")]),
) as Record<(typeof KINDS)[number], string>;

const serve = readFileSync(join(root, "scripts/kit/serve.mjs"), "utf8");

// --- the module the studio imports ----------------------------------------

// JSON.stringify, not a template literal. That is the whole point: a backtick
// or a ${ in someone's template can no longer end the string.
const record = (byKind: Record<string, string>) =>
    KINDS.map((kind) => `    ${JSON.stringify(kind)}: ${JSON.stringify(byKind[kind])},`).join("\n");

const module = `// Generated by scripts/build-templates.mts. Do not edit.
//
// The source is public/templates/<kind>/index.html. Edit those, then run
// \`npm run templates:build\`.

export const TEMPLATE_HTML: Record<string, string> = {
${record(html)}
};

// The same readme the downloadable kits carry, so a kit built in the browser
// and a kit zipped here cannot describe themselves differently.
export const TEMPLATE_README: Record<string, string> = {
${record(readme)}
};

/** scripts/kit/serve.mjs, verbatim. The local loop, whoever assembled the kit. */
export const KIT_SERVE = ${JSON.stringify(serve)};

export const TEMPLATE_KINDS = ${JSON.stringify(KINDS)} as const;
`;

const target = join(root, "src/lib/templates.generated.ts");
const before = existsSync(target) ? readFileSync(target, "utf8") : "";
if (before !== module) writeFileSync(target, module);

// --- the starter kits ------------------------------------------------------

mkdirSync(join(root, "public/templates"), { recursive: true });

for (const kind of KINDS) {
    const archive = zip([
        { name: "index.html", data: html[kind] },
        { name: "README.md", data: readme[kind] },
        { name: "serve.mjs", data: serve },
    ]);
    writeFileSync(join(root, "public/templates", `${kind}.zip`), archive);
}

// --- the bundler kit --------------------------------------------------------
//
// Not a runtime kind. It produces the same single document the other four do
// and is a different way of arriving at one, so it stays out of the catalog
// and out of the module the studio imports.

const bundlerDir = join(root, "public/templates/bundler");

/**
 * The dev harness, taken from the vanilla template.
 *
 * Copied in here rather than written twice. The shell in the repository
 * carries a `// alea:harness` line and is not runnable on its own, which costs
 * nothing: this kit is built before it is opened either way.
 */
const HARNESS = /\/\/ alea:harness:start\n([\s\S]*?)\n\s*\/\/ alea:harness:end/;
const harness = html.vanilla.match(HARNESS)?.[1];
if (!harness) {
    console.error("No harness markers in public/templates/vanilla/index.html");
    process.exit(1);
}

const shell = readFileSync(join(bundlerDir, "src/index.html"), "utf8");
const filled = shell.replace(/^\s*\/\/ alea:harness\s*$/m, () => harness);
if (filled === shell) {
    console.error("No `// alea:harness` line in the bundler shell");
    process.exit(1);
}

writeFileSync(
    join(root, "public/templates", "bundler.zip"),
    zip([
        { name: "src/index.html", data: filled },
        { name: "src/sketch.js", data: readFileSync(join(bundlerDir, "src/sketch.js"), "utf8") },
        { name: "build.mjs", data: readFileSync(join(bundlerDir, "build.mjs"), "utf8") },
        { name: "serve.mjs", data: readFileSync(join(bundlerDir, "serve.mjs"), "utf8") },
        { name: "package.json", data: readFileSync(join(bundlerDir, "package.json"), "utf8") },
        { name: "README.md", data: readFileSync(join(bundlerDir, "README.md"), "utf8") },
    ]),
);

console.log(
    `templates: ${KINDS.length} kinds, module ${before === module ? "current" : "written"}, ${KINDS.length + 1} kits zipped`,
);
