/**
 * Write the static brand assets.
 *
 *   npx tsx scripts/build-icons.mts
 *
 * The compact mark ignores the seed, so these files are stable and belong in
 * the repo rather than being rendered per request.
 */
import { renderLogo, CANONICAL_SEED } from "../src/lib/logo"
import { writeFileSync } from "node:fs"
import { resolve, dirname } from "node:path"
import { fileURLToPath } from "node:url"

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..")

// The favicon set is generated by RealFaviconGenerator and lives in public/:
// favicon.svg, favicon.ico, the 96px png, the apple touch icon and the two
// manifest icons. They are static files and this script leaves them alone.

// The full mark, for anywhere that wants the real thing as a file.
writeFileSync(
  resolve(root, "public/mark.svg"),
  renderLogo({
    seed: CANONICAL_SEED,
    size: 512,
    stroke: "#d9b46a",
    background: "#0f1b1a",
  }),
)

console.log("wrote public/mark.svg")
