/**
 * Turn the template files into the module the studio imports, and into a
 * starter kit somebody can download and work in.
 *
 * The templates used to be backtick literals inside templates.ts, where nobody
 * could find them and where a single backtick ended the literal and broke the
 * module. The files under public/templates are the source now.
 *
 *   npm run templates:build
 *
 * Runs before dev and before build, so neither the generated module nor the
 * kits can be stale.
 *
 * Written as TypeScript and run under tsx, alongside the rest of the source.
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { zip } from "./lib/zip.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const KINDS = ["vanilla", "svg", "p5", "custom"] as const;

const LABEL: Record<string, string> = {
    vanilla: "Canvas 2D",
    svg: "SVG",
    p5: "p5.js",
    custom: "Custom runtime",
};

const missing = KINDS.filter((k) => !existsSync(join(root, "public/templates", k, "index.html")));
if (missing.length > 0) {
    console.error(`No template for: ${missing.join(", ")}`);
    process.exit(1);
}

const html = Object.fromEntries(
    KINDS.map((k) => [k, readFileSync(join(root, "public/templates", k, "index.html"), "utf8")]),
) as Record<(typeof KINDS)[number], string>;

const readme = Object.fromEntries(
    KINDS.map((k) => [k, readFileSync(join(root, "public/templates", k, "README.md"), "utf8")]),
) as Record<(typeof KINDS)[number], string>;

const serve = readFileSync(join(root, "scripts/kit/serve.mjs"), "utf8");

// --- the module the studio imports ----------------------------------------

// JSON.stringify, not a template literal. That is the whole point: a backtick
// or a ${ in someone's template can no longer end the string.
const record = (byKind: Record<string, string>) =>
    KINDS.map((kind) => `    ${JSON.stringify(kind)}: ${JSON.stringify(byKind[kind])},`).join("\n");

const module = `// Generated by scripts/build-templates.mts. Do not edit.
//
// The source is public/templates/<kind>/index.html. Edit those, then run
// \`npm run templates:build\`.

export const TEMPLATE_HTML: Record<string, string> = {
${record(html)}
};

// The same readme the downloadable kits carry, so a kit built in the browser
// and a kit zipped here cannot describe themselves differently.
export const TEMPLATE_README: Record<string, string> = {
${record(readme)}
};

/** scripts/kit/serve.mjs, verbatim. The local loop, whoever assembled the kit. */
export const KIT_SERVE = ${JSON.stringify(serve)};

export const TEMPLATE_KINDS = ${JSON.stringify(KINDS)} as const;
`;

const target = join(root, "src/lib/templates.generated.ts");
const before = existsSync(target) ? readFileSync(target, "utf8") : "";
if (before !== module) writeFileSync(target, module);

// --- the starter kits ------------------------------------------------------

mkdirSync(join(root, "public/templates"), { recursive: true });

for (const kind of KINDS) {
    const archive = zip([
        { name: "index.html", data: html[kind] },
        { name: "README.md", data: readme[kind] },
        { name: "serve.mjs", data: serve },
    ]);
    writeFileSync(join(root, "public/templates", `${kind}.zip`), archive);
}

console.log(
    `templates: ${KINDS.length} kinds, module ${before === module ? "current" : "written"}, kits zipped`,
);
